language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-siiffos' ]; then cd .. && eval "mv $currentfolder generator-siiffos" && cd generator-siiffos; fi

