language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-breizhcamp' ]; then cd .. && eval "mv $currentfolder generator-breizhcamp" && cd generator-breizhcamp; fi
